### ISSUE TITLE
Rename the library

### ISSUE THREAD

**Issue by franciscop** [Flet/semistandard#102]
`semistandard` name looks like it's a sub-step of `standard`, so I suggest renaming this project and properly documenting it not just as a copy/paste of `standard`. I can help a with the documentation. As the name for the library I propose:

### `default`

PS, this is exactly what I was looking for. I love everything from standard except for the *no semicolons* rule, which seems idiotic to have to write this:

```js
foo()
;[1,2,3].forEach(bar)
```

**Comment by bnolan** [comment]
I think the name is great. :D

**Comment by zaynv** [comment]
> PS, this is exactly what I was looking for. I love everything from standard except for the no semicolons rule, which seems idiotic to have to write this:

```javascript
foo()
;[1,2,3].forEach(bar)
```

^ No one really writes code like that. It would probably look more like this:

```javascript
foo()
var nums = [1, 2, 3]
nums.forEach(bar)
```

I haven't really encountered a case where I need to create an array and then do something with it right away like that. I think code like this is a lot better because having a variable name makes the code clearer as well.

**Comment by Flet** [comment]
Thanks for the feedback @franciscop, I'm glad you're enjoying it 😄 

We'll keep the name `semistandard` for now because `default` is taken in npm 😉 

This is always an option 😁:
```bash
alias default=semistandard
```
