### ISSUE TITLE
Relate the version number with "standard"

### ISSUE THREAD

**Issue by gsklee** [Flet/semistandard#15]
My guess is `semistandard` only differs from "standard" in regard of semicolon issues; therefore, can it be reflected in `semistandard`'s version number that which upstream version it corresponds to? For example [esprima-fb](https://www.npmjs.com/package/esprima-fb) is using some weird-looking yet effective version scheme to indicate its relationship with the upsteam.

**Comment by Flet** [comment]
This is difficult because the `standard` package version will be bumped when the rules change or when  changes happen to the CLI code itself which may not be brought over. This could lead to bumping a version of `semistandard` even if no rules changed, which is not the greatest.

Ideally, the `standard` eslint rules themselves would have their own semver separate from the CLI engine code. Then `semistandard` could follow suit and we could synchronize the semver numbers without a lot of mess... 

I've proposed putting `standard` rules in their own module here https://github.com/feross/standard/issues/132

Regardless, I agree that we need to make it clear how up-to-date `semistandard` is in regards to `standards` rules. Encoding additional data into the version number is a bit funky though. Would it help if the information was more prominent? at the top of the README or part of the CLI messaging?

**Comment by gsklee** [comment]
@Flet Yep certainly, for example my https://github.com/gsklee/foundation.css is doing that exactly.

**Comment by Flet** [comment]
So, now we've switched to using `eslint-config-semistandard`, which extends `eslint-config-standard`. Its set to automagically use the latest non-breaking version of the standard config on every install of semistandard.... so I guess the answer is going to always be "the latest non-breaking version of standard" now...

**Comment by gsklee** [comment]
@Flet Sounds great!
