### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by bnolan** [Flet/semistandard#27]
https://travis-ci.org/Flet/semistandard/jobs/73421498#L252

**Comment by Flet** [comment]
Some repose being tested were not compliant. The latest version of `eslint` fixed some bugs around indentation and there were also some additional rules added for better coveraged in `standard`.

I added a bunch more repositories to the test and commented out the ones that are failing due to being on an older `semistandard` version. Tests should be passing with the new prereleased `7.0.0-0`

also, @bnolan, some scenevr repos in there were not up to date :)

**Comment by Flet** [comment]
Build is passing now
